### ISSUE TITLE
Increase the allowed version constraints in metadata.json

### ISSUE THREAD

**Issue by stevenrombauts** [logdna/puppet-logdna#4]
The puppetlabs/apt and puppetlabs/stdlib version are both restricted to 4.x versions. 

We require the latest 6.x version of puppetlabs/apt but this module was preventing us from doing that.

**Comment by smusali** [comment]
@stevenrombauts, now all changes have just been merged and published onto `forge` as `v0.6.0`. Thanks for contribution!

**Comment by stevenrombauts** [comment]
@smusali That's great, thanks for your help!
